---

- hosts: all
  tasks:

  - name: install apache and php packages and update the repository
    package:
      name:
        -  "{{ apache_pkg }}"
        -  "{{ php_pkg }}"
      state: latest
      update_cache: yes
