---
- hosts: all
  pre_tasks:

  - name: Update repo for ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    tags: always

  - name: Update repo for centos
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"
    tags: always

- hosts: web
  tasks:

    - name: Install apache and php
      dnf:
        name:
          - httpd
          - php
        state: present
      tags: web
    
    - name: Copy site file to the web server
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
      tags: copy

- hosts: db
  tasks:

    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"
      tags: db


